### ISSUE TITLE
Build error when -Dtarget=

### ISSUE THREAD

**Issue by taylowar** [G3bE/raylib-zig#104]
Any idea on what I am doing wrong?

![image](https://github.com/Not-Nik/raylib-zig/assets/32261878/a374b7f2-d245-465b-a3a7-022b51673771)

**Comment by Not-Nik** [comment]
What's your host system? If you're not on Linux you probably need Linux' GL and X11 libraries to cross-compile. If you are on Linux, why are you specifying the target? And why don't you have OpenGL installed? Maybe you are missing graphics drivers completely, e.g. if you are on a headless system.

**Comment by taylowar** [comment]
I think it is some issues on the raylib.zig part with how they handle parsing the target

**Comment by Not-Nik** [comment]
So is it on our side? Or on Zig's?
