### ISSUE TITLE
Build issue with project_setup.sh and manual instructions

### ISSUE THREAD

**Issue by arider** [G3bE/raylib-zig#119]
Hi, I only just started tinkering with zig, so maybe this is a trivial fix.

zig build works fine in both manual and script setup.  Running "zig run src/main.zig" gives "
main.zig:3:20: error: no module named 'raylib' available within module main
const rl = @import("raylib");
"

**Comment by Not-Nik** [comment]
Use the `run` target to execute your program, i.e. `zig build run`
