### ISSUE TITLE
No type definitions for lib? ZLS

### ISSUE THREAD

**Issue by krymancer** [G3bE/raylib-zig#132]
This seem to be related with #42 

I just created a project with zig init and I don't have any autocomplete or any information on hover.

I tried using the `project_setup.ps1` on windows and `project_setup.sh` (in wsl and in another machine that I have arch installed) and the same is occurring.

Autocomplete for std working fine so don't seem an issue with ZLS.

rl has `unknow` type
![image](https://github.com/user-attachments/assets/8e449ca1-5a03-48be-a7fb-499ea5085a76)

std has `type` type
![image](https://github.com/user-attachments/assets/e4cdba08-a8e3-4bc7-96be-17469ff7e46d)

No autocomplete for rl
![image](https://github.com/user-attachments/assets/826ffe30-6f95-4772-82be-a97dc8e1838c)

Autocomplete for std
![image](https://github.com/user-attachments/assets/65e8ddcc-1b31-4851-90aa-cfdc76e22dd1)

**Comment by Not-Nik** [comment]
This is pretty surely a different issue. Could be related to zigtools/zls#1927, but I'm not sure what your setup looks like. If the program builds correctly I don't see how this is a raylib-zig issue. Take this up with ZLS people
