### ISSUE TITLE
Building For GLES2

### ISSUE THREAD

**Issue by wwderw** [G3bE/raylib-zig#133]
I'm on a Linux machine trying to cross compile the program itself.  I think I have a successful build of raylib itself with GLES for windows (it at least didn't output any errors), but it for some reason cannot find my dyn windows libs despite my addLibraryPath being correctly set to where I have vendored all my dyn libs.  Linux builds and runs fine, but for some reason I can't build Windows.

I do have my include/lib paths setup before any linksystemlibrary calls as well.

I have tried on Zig 0.13 and on today's daily build.

Appreciate the help.

**Comment by Not-Nik** [comment]
Please provide errors and your `build.zig`

**Comment by wwderw** [comment]
I got it to work by using the CLI directly invoking everything.  I saw one of the daily builds had broken my build.zig files for other projects, so I thought I would try that and it worked like a charm.  So I'm thinking that something like that is going on.
