### ISSUE TITLE
`drawTextCodepoints` is missing

### ISSUE THREAD

**Issue by lhk** [G3bE/raylib-zig#135]
I'd like to draw text in the Devanagari script. Like this for example: मेरा नाम लार्स है

It seems that the wrapper only exposes `drawTextCodepoint` which takes in a single `i32` codepoint. With that, I think the best I can come up with is this:
```
        const view = try std.unicode.Utf8View.init("मेरा नाम लार्स है");
        var it = view.iterator();
        var offset: f32 = 0;
        while (true) {
            offset += 10;
            const codepoint = it.nextCodepoint() orelse break;
            const codepointi32: i32 = @as(i32, codepoint);
            const pos2 = rl.Vector2.init(100 + offset, 100);
            rl.drawTextCodepoint(devanagariFont, codepointi32, pos2, 20, rl.Color.black);
        }
```

for completeness, the font is loaded with:
```
    // Block from U+0900 to U+097F. This block was introduced in Unicode version 1.1 (1993). It contains 128 codepoints.
    var codepoints = std.ArrayList(i32).init(allocator);
    defer codepoints.deinit();

    var character: i32 = 0x0900;
    while (character <= 0x097F) {
        try codepoints.append(character);
        character += 1;
    }

    const devanagariFont = rl.loadFontEx("assets/NotoSerifDevanagari_Condensed-Bold.ttf", 20, codepoints.items);
    defer rl.unloadFont(devanagariFont);
```

This way of drawing the example text snippet looks like this:
![image](https://github.com/user-attachments/assets/baf87f08-6ec9-47e1-b427-f440ca758191)

Maybe `drawTextCodepoints` would correctly deal with merging codepoints into single characters? But this function doesn't seem to be exposed by the wrapper.

**Comment by Not-Nik** [comment]
`drawTextCodepoints` was marked for manual implementation back when I added proper slice support, but I must've forgot to actually put it in. Thanks for the catch!
