### ISSUE TITLE
Building examples

### ISSUE THREAD

**Issue by Zenchess** [G3bE/raylib-zig#14]
Hi, I have tried using this library, here are the issues I've had with latest zig dev:

first , there is a compilation error in lib.zig line 65 something to do with the \\ lines ,
C:\zigprojects\zigraylib\raylib-zig\lib.zig:65:27: error: expected ',', found invalid bytes
                \\Warning:
                          ^
C:\zigprojects\zigraylib\raylib-zig\lib.zig:66:72: note: invalid byte: 'd'
                \\Unable to fetch git submodule(s) Assuming package folder is not under

 so I changed that to a simple string, and it seemed to work.  

Now when I do zig build examples I get the error:C:\zigprojects\zigraylib\raylib-zig\examples\core\basic_window.zig:17:5: error: use of undeclared identifier 'InitWindow'
    InitWindow(screenWidth, screenHeight, "raylib-zig [core] example - basic window");

I haven't changed anything, not sure if I"m doing something wrong.  I see on top of the file the usingnamespace @import("raylib");

(i'm developing on windows)

**Comment by nektro** [comment]
the first is about files not being allowed to have `\r\n` line endings. change all the zig files to be `\n` to fix it
