### ISSUE TITLE
Adding a custom html file for WASM build

### ISSUE THREAD

**Issue by CashWasabi** [G3bE/raylib-zig#140]
When compiling for `emscripten` target there is an option to also use a custom `html` file.
I think this could be enabled by adding an argument to the `linkWithEmscripten` function inside `emcc.zig`.
I already tested it out with a harcoded path and it works.

Is this something you would like to add?

If you want I could just create a PR that then enables the option to parse a custom html file if needed. 

The benefit here is that you can e.g. just have a simple canvas instead of the template html file which is normally generated.

**Comment by Not-Nik** [comment]
Create a PR, I'll review it then
