### ISSUE TITLE
Adding raylib-extras

### ISSUE THREAD

**Issue by ZackeryRSmith** [G3bE/raylib-zig#146]
Is adding any of the [raylib-extras](https://github.com/raylib-extras/) out of this projects scope? I would love to be able to have handy libraries like [reasings](https://github.com/raylib-extras/reasings) and built-in to these bindings.

Many of the extras are written in languages other than C. I find that having these (if not in the main bindings) in some side repo. I am more than willing to make a PR and do this myself. That is up to you in the end. Would hate to work on them to find out it's out of the bindings scope.

**Comment by Not-Nik** [comment]
I understand the want for such helper libraries, but they increase the scope of this project too much. reasings specifically is a standalone header library, and Zig's builtin @cImport should "just work" without a binding. The other libraries will probably also work like that, even though you'll have to add the .c files to your build manually.
