### ISSUE TITLE
Microzig cannot build regz

### ISSUE THREAD

**Issue by rjsstewart** [G3bE/raylib-zig#148]
The following is my attempt to clone regz and build it:

git clone --recursive https://github.com/ZigEmbeddedGroup/regz.git
Cloning into 'regz'...
remote: Enumerating objects: 4984, done.
remote: Counting objects: 100% (292/292), done.
remote: Compressing objects: 100% (92/92), done.
remote: Total 4984 (delta 243), reused 208 (delta 199), pack-reused 4692 (from 1)
Receiving objects: 100% (4984/4984), 6.14 MiB | 10.24 MiB/s, done.
Resolving deltas: 100% (1628/1628), done.
[bob@gamer microzig]$ cd regz
[bob@gamer regz]$ zig build
/home/bob/zig/microzig/regz/build.zig:7:21: error: root struct of file 'std' has no member named 'build'
pub fn build(b: *std.build.Builder) !void {
                 ~~~^~~~~~
/usr/lib/zig/std/std.zig:1:1: note: struct declared here
pub const ArrayHashMap = array_hash_map.ArrayHashMap;
^~~
referenced by:
    runBuild__anon_8822: /usr/lib/zig/std/Build.zig:2115:50
    main: /usr/lib/zig/compiler/build_runner.zig:301:29
    remaining reference traces hidden; use '-freference-trace' to see all reference traces

I'm running on a current archlinux and sucessfully installed zig through a snap package and successfully built an stm32 example before trying this.

Bob Stewart

**Comment by Not-Nik** [comment]
What does this have to do with raylib-zig?
