### ISSUE TITLE
Q: How can I link it as a shared library

### ISSUE THREAD

**Issue by horenso** [G3bE/raylib-zig#154]
Hi,
could you please explain  how I can link `raylib-zig` as a shared library.
I need this because I split my game into a shared library and an executable,
and I want to use `raylib-zig` in both the executable and the shared library.
Thank you very much for the awesome bindings!

**Comment by Not-Nik** [comment]
Pass shared as a build option to the rlz dependency:
```zig
.{
    .target = target,
    .optimize = optimize,
    .shared = true,
}
```
