### ISSUE TITLE
Does not work with Wayland

### ISSUE THREAD

**Issue by Raff727** [G3bE/raylib-zig#157]
I am running Debian 13 testing with the standard configuration of Gnome which uses Wayland

First of all normal raylib examples compile and run normally so it's not an issue with something outside of these bindings.
What i have tried for raylib-zig:
- cloning raylib-zig locally and changing linux_display_backend to .Wayland
- setting .linux_disply_backend = rlz.LinuxDisplayBackend.Wayland for raylib_dep
- adding these linksSystemLibrarys for raylib_artifact, exe and the exe in the local raylib-zig
  as they are what the build.zig of raylib uses

`.linkSystemLibrary("wayland-client"); `
`.linkSystemLibrary("wayland-cursor");`
`.linkSystemLibrary("wayland-egl");`
`.linkSystemLibrary("xkbcommon");`

and yet even though it compiles i get this error when i try to run the program:
INFO: Initializing raylib 5.5-dev
INFO: Platform backend: DESKTOP (GLFW)
INFO: Supported raylib modules:
INFO:     > rcore:..... loaded (mandatory)
INFO:     > rlgl:...... loaded (mandatory)
INFO:     > rshapes:... loaded (optional)
INFO:     > rtextures:. loaded (optional)
INFO:     > rtext:..... loaded (optional)
INFO:     > rmodels:... loaded (optional)
INFO:     > raudio:.... loaded (optional)
WARNING: GLFW: Error: 65544 Description: Wayland: Failed to load libwayland-client
WARNING: GLFW: Failed to initialize GLFW
Segmentation fault at address 0x0
???:?:?: 0x0 in ??? (???)
fish: Job 1, './zig-out/bin/tetris' terminated by signal SIGABRT (Abort)

**Comment by Not-Nik** [comment]
Could you try, in addition to your `linkSystemLibrary` calls, to add `raylib_artifact.defineCMacro("_GLFW_WAYLAND", null);`

**Comment by Raff727** [comment]
Sadly this doesn't change anything

**Comment by LunarWarg** [comment]
On arch with wayland (hyprland) I can't reproduce this.
![2024-10-17-094854_hyprshot](https://github.com/user-attachments/assets/c5d80e18-22d2-4029-8261-ef8db5fb2dce)

Are you using Nvidia?
https://wiki.debian.org/Wayland :
"[GDM](https://wiki.debian.org/GDM) (GNOME Display Manager) will automatically use Wayland when supported, except when using the proprietary NVIDIA driver, in which case it will fall back to X11 due to instability."

**Comment by Raff727** [comment]
No I'm using an integrated specifically that of an i7-1185G7.
And `echo "$XDG_SESSION_TYPE` gives me wayland,
as well as the examples of normal raylib which give the same INFO statement as in your screenshot.

**Comment by myQwil** [comment]
> normal raylib examples compile and run normally so it's not an issue with something outside of these bindings.

I also noticed this. The solution for me was to have both raylib and raylib-zig as dependencies and then link the library with the module like so:

```zig
const raylib_dep = b.dependency("raylib", .{
    .target = target, .optimize = optimize,
});
const rayzig_dep = b.dependency("raylib_zig", .{
    .target = target, .optimize = optimize,
});
const raylib_artifact = raylib_dep.artifact("raylib");
const rayzig_module = rayzig_dep.module("raylib");
rayzig_module.linkLibrary(raylib_artifact);
```

**Comment by Raff727** [comment]
Still doesn't change anything, the same "... Failed to load libwayland-client" error remains.
I tried looking into what zig links in the build process as this seems like a linking issue. With `zig build --verbose-link` it gives some more insight and confuses me even more: it outputs a long ld.lld command which does include the correct libwayland-client.so but it states that the command had an error and failed. Yet still produces a working executable.

**Comment by Not-Nik** [comment]
Sounds like a Zig issue, opening an issue with is probably best.

**Comment by Raff727** [comment]
I tried to get zig to first compile an object file and then link it separately, trying to force it to link against libwayland-client. But after throwing a bunch of options at it my program just crashes with a SIGFPE.
I think I will have to postpone working on this further until I understand how to get it to link properly. For now, I will move this to the official zig repo as it seems like zig ignores my linking of libwayland-client because it is not explicitly used in my program.
