### ISSUE TITLE
Can I use Raylib from the project folder?

### ISSUE THREAD

**Issue by X-Ninja-dev** [G3bE/raylib-zig#164]
Sorry, I do not know why my question was posted before I got to explain.

I would like to use a local version of Raylib in my project folder instead of relaying on the globally install version. Is this possible?

**Comment by znichola** [comment]
It does not use on a globally installed version, the build.zig.zon is what specifies how to get the library, it's a link to a git repo. So your project will point to this repo, then this repo will point to raylib. 

If you use something like vscode you can `ctrl+click` on `rlz` on the first line of the build.zig, `const rlz = @import("raylib-zig");` and it will open the file, somewhere in appdata, (if your on windows). Then from there you can `ctrl+click` to find the raylib library.

---

You can also modify the build to use a subfolder as the source for the module, but I've not done this so can't really advise. [This](https://github.com/ryupold/raylib.zig?tab=readme-ov-file#usage) might be helpful, it's from another binding for raylib in zig.

**Comment by X-Ninja-dev** [comment]
Sorry for the late reply and thank you for the answer.

I will look into it and see which solution I like best.

**Comment by Not-Nik** [comment]
Alternatively, the Zig package manager also allows to specify a path to a package, so you could clone this binding and raylib, and then change the bindings `build.zon` to use the cloned raylib, and your `build.zon` to use the cloned binding.
