### ISSUE TITLE
Error with textFormat

### ISSUE THREAD

**Issue by ttmso** [G3bE/raylib-zig#168]
Error:
`lib\raylib.zig:2157:14: error: no field named 'Struct' in enum '@typeInfo(builtin.Type).@"union".tag_type.?'`

Line of code:
`rl.drawText(rl.textFormat("FPS: %i", .{rl.getFPS()}), 10, 10, 20, rl.Color.white);`

I setup raylib as the readme said and my Zig version is 0.14.0-dev.

**Comment by Not-Nik** [comment]
We'll [cross that bridge when we come to it](https://github.com/Not-Nik/raylib-zig/blob/devel/CONTRIBUTING.md#updates-to-the-zig-version).
