### ISSUE TITLE
SetConfigFlags doesn't accept enum

### ISSUE THREAD

**Issue by mgord9518** [G3bE/raylib-zig#25]
When trying to use SetConfigFlags, a project will not build unless using Zig's @enumToInt function as it appears to accept only `c_uint` and not the defined ConfigFlags enum type.

Example code:```
// Doesn't build
rl.SetConfigFlags(rl.ConfigFlags.FLAG_WINDOW_UNFOCUSED);

// Works
rl.SetConfigFlags(@enumToInt(rl.ConfigFlags.FLAG_WINDOW_UNFOCUSED));
```

**Comment by Not-Nik** [comment]
Thanks for the report

**Comment by mgord9518** [comment]
@Not-Nik unrelated and out of curiosity, I'm new to Zig but isn't the convention camelCase for functions? Is this wrapper just using PascalCase because it's what RayLib uses by default?

**Comment by Not-Nik** [comment]
It's because that's what raylib uses, but you're right, it should be changed

**Comment by Not-Nik** [comment]
I looked a bit into it, and since I can't find a way to tell Zig that an external functions has a certain link-time symbol with a different name than the one it is expecting without creating an entirely new function, the function names will stay as is.
