### ISSUE TITLE
Expose access to Raylibs compile-time config flags

### ISSUE THREAD

**Issue by AlxHnr** [G3bE/raylib-zig#28]
The default CMake build allows configuring [compile-time library flags](https://github.com/raysan5/raylib/blob/master/cmake/CompileDefinitions.cmake) for Raylib. An example use case would be disabling the default screenshot button (F12) so one can use this key for something else. It would be great if there would be a way to pass in a Zig config object when setting up the build.

**Comment by Not-Nik** [comment]
This can't be done currently because this binding uses the `src/build.zig` file in the main raylib repository to build raylib. You could create a PR there to update the `addRaylib` function. If you do that please reopen this issue and I'll add it with the next release.

**Comment by RokasPuzonas** [comment]
For anyone that stumbles upon this issue, I figured out a way to set compile-time library flags without updating the raylib library. In my case I wanted to add support for parsing JPG images. 

You can call the `.defineCMacro()` method in the raylib artifact to configure what you want to be enabled. So if you used the [project_setup](https://github.com/Not-Nik/raylib-zig/blob/devel/project_setup.sh) script, you can enable JPG file format like this:
```diff
pub fn build(b: *std.Build) !void {
    // ...
    
    const raylib = raylib_dep.module("raylib");
    const raylib_artifact = raylib_dep.artifact("raylib");
+   raylib_artifact.defineCMacro("SUPPORT_FILEFORMAT_JPG", null);

    // ...
}
```

@Not-Nik Maybe it would be good to update the README to show that you can do this?

**Comment by Not-Nik** [comment]
Done!
