### ISSUE TITLE
No Autocomplete For Zig LSP

### ISSUE THREAD

**Issue by Umi-L** [G3bE/raylib-zig#42]
Hello! Recently while using this library I noticed that the zig LSP was unable to find any of the function signatures for autocompletion. The type for the Raylib include is unknown and there are no autocomplete. I have included screenshots of both of these things below.

while searching for solutions I found another person who uploaded a youtube video had the same issue.

[here is that video with the timestamp included.](https://youtu.be/TxKRSSDC-Ig?t=997)

I am using the stock LSP plugin for vscode and the latest stable release of zig. Any help is appreciated; thanks!

![image](https://github.com/Not-Nik/raylib-zig/assets/76528710/f6623881-c9dc-40c7-9b4f-a7ce004dde87)

![image](https://github.com/Not-Nik/raylib-zig/assets/76528710/c68bacf5-d43f-42cd-af2e-8e542bdd74dc)

**Comment by Not-Nik** [comment]
Seems to be related to https://github.com/zigtools/zls/issues/1218, but we can't just remove the `usingamespace`, because the function definitions are generated by a script. I'll look into possible restructuring of how the library files are created to avoid this issue

**Comment by Not-Nik** [comment]
Should be fixed in af773c79e2c8cca590b726be00b46c17f0ab8fed

**Comment by Not-Nik** [comment]
From my own testing this works properly now
