### ISSUE TITLE
flags incorrectly converted in the python generator

### ISSUE THREAD

**Issue by Veeloxfire** [G3bE/raylib-zig#43]
the `SetWindowState`, `ClearWindowState` and `SetConfigFlags` functions are manually set to convert their flags argument to the `ConfigFlags` type

However, this is incorrect. These functions are desgined to take multiple flags not just one
Its UB in zig to cast to an enum from integer which doesn't represent one of the values

Because of this, trying to pass multiple flags at once to any of these will cause Zig to invoke UB (and even panic with safety checks enabled)

**Comment by Not-Nik** [comment]
I'll keep these as integers for now, until we find a better solution
