### ISSUE TITLE
Implement system-raylib flag

### ISSUE THREAD

**Issue by misuba** [G3bE/raylib-zig#54]
So unless I'm misreading the code, this flag is not implemented and there's currently no way to use the system raylib instead of a fresh download, yes?

(This is relevant to me as raylib doesn't seem to want to compile on MacOS as of an Xcode update a couple days ago, but I got it installed via Homebrew first.)

**Comment by Not-Nik** [comment]
I don't think the zig package manager supports this kind of behaviour, and I don't have plans to reimplement this flag.

If your raylib build does fail with the Zig c compiler, please create an issue on Zig's repository and take it up with them

**Comment by Not-Nik** [comment]
I just realised that, of course, you don't need to use the `link` function provided. Instead just call `exe.linkSystemLibrary("raylib");`. You may also need to link some system specific libraries, but you can just copy the switch statement from the `build.zig`.
