### ISSUE TITLE
how do I include other libs (web build)

### ISSUE THREAD

**Issue by dynnamitt** [G3bE/raylib-zig#60]
As a zig beginner I find it unclear how I can link more libs into the web build part. (metal/os build did work fine)
Could comments or doc show a sample on this. (zflecs in my case)
I used the `project_setup.sh` as explained.

**Comment by Not-Nik** [comment]
Did you try just linking normally to `exe_lib`?

**Comment by dynnamitt** [comment]
What is normal?

**Comment by dynnamitt** [comment]
https://github.com/dynnamitt/uber-grafen/blob/main/build.zig

I could not figure out how to use exe_lib here no

**Comment by Not-Nik** [comment]
> What is normal?

Normal would be `exe_lib.linkLibrary`

As this is not directly related to raylib-zig I'm closing this issue
