### ISSUE TITLE
attempting to import both raylib and raylib-math fails

### ISSUE THREAD

**Issue by erez-avidan** [G3bE/raylib-zig#69]
when wanting to use the math library, importing it like so:

``` zig
const rl = @import("raylib");
const rlm = @import("raylib-math");
```
results in a failure to compile with the following error:
`raylib-zig\lib\raylib-zig.zig:1:1: error: file exists in multiple modules`

it does work in the example files (in camera2d.zig for example), but not when using it from outside the raylib-zig folder itself

**Comment by Not-Nik** [comment]
Fixed in f8735a8cc79db221d3c651c93778cfdb5066818d
