### ISSUE TITLE
Feature request: bindings for Raylib `rlgl` OpenGL abstraction layer

### ISSUE THREAD

**Issue by blazkowolf** [G3bE/raylib-zig#77]
## `rlgl`

Raylib provides [`rlgl`](https://github.com/raysan5/raylib/blob/master/src/rlgl.h) which is a cool abstraction yielding an OpenGL 1.1 "feeling" API. 

## Value proposition (or lack thereof)

This would be really cool to add to the existing Zig bindings in this repo since there's times the higher-level Raylib primitives don't do the job. Granted, this is rarely the case, but I recently ran into this scenario and I was looking to use some of these `rlgl` functions from this repo.

---

Apologies if this is not the forum for this kind of request. Thanks for the great work on providing a great Zig experience for Raylib.

**Comment by Not-Nik** [comment]
This would definitely be a nice addition. I'll look into the details when I have a bit of time to spare, maybe this weekend.

**Comment by Not-Nik** [comment]
lmao my force pushes got EXPOSED
