### ISSUE TITLE
Building for Wasm "error: unable to spawn mkdir: FileNotFound"

### ISSUE THREAD

**Issue by JoeRocky** [G3bE/raylib-zig#86]
Hello, I'm trying to build my raylib-zig project, that is working fine if I build it for my OS (Windows), to wasm. 
When I run ``zig build -Dtarget=wasm32-emscripten --sysroot C:\emsdk\upstream\emscripten`` i get the following error:
```ts
install
└─ run C:\emsdk\upstream\emscripten\emcc.bat
   └─ run mkdir failure
error: unable to spawn mkdir: FileNotFound

Build Summary: 4/7 steps succeeded; 1 failed (disable with --summary none)
install transitive failure
└─ run C:\emsdk\upstream\emscripten\emcc.bat transitive failure
   └─ run mkdir failure
error: the following build command failed with exit code 1:
```

I also ran
```
emsdk install latest
emsdk activate latest --permanent
```
just to make sure but it didnt help...

**Comment by JoeRocky** [comment]
ok i figured out that line 94 in the ``emcc.zig`` file is causing the issue:
``const mkdir_command = b.addSystemCommand(&[_][]const u8{ "mkdir", "-p", emccOutputDir });``

**Comment by Not-Nik** [comment]
`mkdir` should still be present on Windows systems, also your initial error looks like it originates in `C:\emsdk\upstream\emscripten\emcc.bat`. Could you check that `mkdir` works on your system and that emcc works properly?

**Comment by eldahine** [comment]
Hi, I'm encountering the same error. This is my first time using Zig.
I'm on the `devel` branch, using Windows 11 and Zig 0.13.0. When I run the command:
```ps
zig build -Dtarget=wasm32-emscripten --sysroot "C:\emsdk\upstream\emscripten"
```
I get the following error:
```ps
install
└─ run C:\emsdk\upstream\emscripten\emcc.bat
   └─ run mkdir failure
error: unable to spawn mkdir: FileNotFound
Build Summary: 5/8 steps succeeded; 1 failed (disable with --summary none)
install transitive failure
└─ run C:\emsdk\upstream\emscripten\emcc.bat transitive failure
   └─ run mkdir failure
error: the following build command failed with exit code 1:
C:\zig-raylib-game\.zig-cache\o\0c522e1745d6b40bc64b3b0e8b6eeb98\build.exe C:\zig\zig-windows-x86_64-0.13.0\zig.exe C:\zig-raylib-game C:\zig-raylib-game\.zig-cache C:\Users\[username]\AppData\Local\zig --seed 0xbb3af7ea -Za21555bea8f8d4b9 -Dtarget=wasm32-emscripten --sysroot C:\emsdk\upstream\emscripten
```
My workaround is to copy the `raylib-zig` to a subdirectory and modify it. This is my `build.zig.zon`:
```zig
.{
    .name = "project_name",
    .version = "0.0.1",
    .dependencies = .{
        .@"raylib-zig" = .{ .path = "libs/raylib-zig" },
    },
    .paths = .{""},
}
```
In `emcc.zig`, I commented out these lines:
```zig
// line 94 // const mkdir_command = b.addSystemCommand(&[_][]const u8{ "mkdir", "-p", emccOutputDir });
// line 104 // emcc_command.step.dependOn(&mkdir_command.step);
```
Then, I manually call `mkdir` to create the output directories.
```ps
mkdir -p zig-out/htmlout 
```
I have no idea why `mkdir` is not accessible to Zig. Manually creating the directory fixed it, and `emcc` works fine.

I kind of wish I had seen JoeRocky's answer sooner. I spent a week tinkering with raylib-zig to finally get it to work. It was already a reported issue. 😅

**Comment by eldahine** [comment]
So, I did some research and I think mkdir is only available inside `CMD` or `PowerShell` on Windows. I might be wrong about this, so please correct me. In the meantime, I replaced the `addSystemCommand` call with the code below:
```zig
try b.build_root.handle.makePath(emccOutputDir);
```
I'm not sure if this is the right way of doing things in Zig, but hey, it works.

**Comment by znichola** [comment]
I had this same issue when building on windows with powershell, @eldahine's solution has fixed it for me.

I've made are the change on a branch from my fork, I also tested by importing from my branch in my `build.zig.zon` on [my project](https://github.com/znichola/unnamed/tree/5120665d7b56f977aafec2dfa364715a121f32d7) and it has fixed it, even though the errors it showed were completely off, missing imports, no absolute path etc. 

---

[znichola/raylib-zig-fork/tree/emsdk-win-mkdir-fix](https://github.com/znichola/raylib-zig-fork/tree/emsdk-win-mkdir-fix)

I can open a PR for this, but I've not got a linux to test it with. Though I could try through WSL ...

**Comment by DanielKMach** [comment]
I found that the equivalent command for Windows would be:

```
cmd /c mkdir zig-out\htmlout
```

This runs `mkdir` via the command line, but Windows doesn’t support the `-p` flag, so it errors if the directory already exists. To handle this, I tried:

```
cmd /c if not exist zig-out\htmlout mkdir zig-out\htmlout
```

Then, I replaced the original line of code with a conditional switch:

```zig
const mkdir_command = switch (builtin.os.tag) {
    .windows => b.addSystemCommand(&.{ "cmd.exe", "/c", "if", "not", "exist", emccOutputDir, "mkdir", emccOutputDir }),
    else => b.addSystemCommand(&.{ "mkdir", "-p", emccOutputDir }),
};
```

This works well! It might be a better approach compared to @eldahine’s suggestion since it keeps the step, rather than running with the function.

**Comment by Not-Nik** [comment]
@DanielKMach awesome, thanks, fixed!
